version: '3'
services:
  ldwizard:
    image: ldwizard/nde:1.0.0
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        CONFIG_FILE: ./webpack/runtimeConfig.ts

    ports:
      - "4000:80"