name: Build

on:
  push:
    branches: [ "*" ]
    paths:
    - "*.json"
    - "yarn.lock"
    - "src/**"
    - "webpack/**"
    - "docker/**"
    - ".github/workflows/build.yml"
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

jobs:

  build:
    name: Build with yarn
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn
      run: |
        npm install --global yarn

    - name: Install Node 18 dependencies
      if: ${{ matrix.node-version == '18.x' }}
      run: |
        yarn global add node-gyp

    - name: Install dependencies
      run: |
        yarn --frozen-lockfile

    - name: Build the LDWizard
      run: |
        yarn build

    - name: Run the ldwizard-build script on default config
      run: |
        yarn ldwizard-build webpack/runtimeConfig.ts


  docker:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        docker build . -f ./docker/Dockerfile -t ldwizard --build-arg CONFIG_FILE=webpack/runtimeConfig.ts
