name: Build

on:
  push:
    branches: [ "*" ]
    paths:
    - "*.json"
    - "package-lock.json"
    - "src/**"
    - "webpack/**"
    - "docker/**"
    - ".github/workflows/build.yml"
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

jobs:

  build:
    name: Build with Node.js
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm ci

    - name: Build the LDWizard
      run: |
        npm run build

    - name: Run the ldwizard-build script on default config
      run: |
        npm exec ldwizard-build webpack/runtimeConfig.ts


  docker:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . -f ./docker/Dockerfile -t ldwizard --build-arg CONFIG_FILE=webpack/runtimeConfig.ts
